### PR TITLE
fix: Cannot read property 'description' of undefined

### PR DESCRIPTION
**Pull request by fatelei**
v2 shema has changed

image

### CODE REVIEW

**Comment by muhserks** [comment]
@bautistaj @fatelei 
Any chance of getting this merged and a new npm package?
❤️

**Comment by fatelei** [comment]
> @bautistaj @fatelei Any chance of getting this merged and a new npm package? ❤️

there is a conflict, i will resolve it

**Comment by gernotk** [comment]
Pretty please?

**Comment by fatelei** [comment]
> Pretty please?

ok

**Comment by fatelei** [comment]
code has been formatted, @gernotk

**Comment by gernotk** [comment]
Pretty please, merge! Thank you.

**Comment by bautistaj** [comment]
The changes were merged and the version in NPM was updated.

**Pull request merged**
